### ISSUE TITLE
FF in Scannet

### ISSUE THREAD

**Issue by guoqingyin** [SamsungLabs/tr3d#10]
Hello, I have read a series of your papers including Imvoxelnet, Fcaf3d, Tr3d. I have a question, have you tried to use feature fusion on Scannet? Does it work well?

**Comment by filaPro** [comment]
Hi @guoqingyin ,
No, we didn't try. But basically I think sampling ~50 images for a scene following ImVoxelNet and add them to TR3D featured with this simple trick should give some benefit to overall accuracy.

**Comment by guoqingyin** [comment]
Thank you for your work and your quick reply. I agree with your methods. For some objects, it is difficult for us to distinguish them from the point cloud, like some flat objects, such as paintings, or cubic objects, such as refrigerators. But for pictures, it is easy to know, so this is also the main purpose of feature fusion. But unfortunately, in SUN-RGBD, there are no such types of objects where all the classes have large geometric distinction beetween each other. @filaPro

**Comment by filaPro** [comment]
Btw following #9 it may be interesting to check more classes on SUN RGB-D dataset:)
