### ISSUE TITLE
Running the pipeline without gpu

### ISSUE THREAD

**Issue by farzanehm-g** [SamsungLabs/tr3d#11]
Hi,
I was wondering if it is possible to run the pipeline with dummy inputs on a machine with no gpus.
Do you have a Dockerfile for that scenario?
If so, I would appreciate if you could share that.

Thank you

**Comment by filaPro** [comment]
Hi @farzanehm-g,
We didn't try to run TR3D without gpu. I think, MinkowskiEngine can be compiled for only cpu. Also you will need to replace our NMS for gpu with cpu version from mmdetection3d.
