### ISSUE TITLE
Cuda Errors During Installation

### ISSUE THREAD

**Issue by mostafa501** [SamsungLabs/tr3d#17]
Hi @filaPro, I tried to use the network, and started using installing required libraries. THere are two methods (manual install and docker file), I started with manual one, but I found too much errors due to versions of libraries and cuda version.
After that I tried to use docker file but I always find this error:
--------------------
"No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
ERROR: failed to solve: process "/bin/sh -c pip install -U git+https://github.com/NVIDIA/MinkowskiEngine@405b39cb7e68c2ec1b4ac8c4b4ca9fa6fcfcb2fc -v --no-deps     --install-option=\"--blas=openblas\"     --install-option=\"--force_cuda\"" did not complete successfully: exit code: 1"
--------------------
Note: my cuda version is 11.1 and cuda version used in docker file is 11.3, is this error due to this? and how can i solve this error?

and is the differenet cuda versions also cause the errors in case of manual install also ? 

Thank you so much.

**Comment by filaPro** [comment]
Is your `cuda` actually installed at `/usr/local/cuda`? For some reason MinkowskiEngine installer doesn't see it there.

**Comment by mostafa501** [comment]
Hello, I am trying to test a point cloud file (chair.bin) using this script (test_demo.py). After too much time, I finally isntalled all required libraries with cuda and solving all errors apeared, however I got this error which I can not solve. Could you please help me? Thank you


[chair_code.zip](https://github.com/SamsungLabs/tr3d/files/13251509/chair_code.zip)
____
da3/envs/TR3D-113/bin/python /media/navlab/GNSS/work/detection/tr3d-main/demo/pcd_demo_used_ok.py
/media/navlab/GNSS/work/detection/tr3d/mmdet3d/models/backbones/mink_resnet.py:10: UserWarning: Please follow `getting_started.md` to install MinkowskiEngine.`
  'Please follow `getting_started.md` to install MinkowskiEngine.`')
/media/navlab/GNSS/work/detection/tr3d/mmdet3d/models/dense_heads/fcaf3d_head.py:8: UserWarning: Please follow `getting_started.md` to install MinkowskiEngine.`
  'Please follow `getting_started.md` to install MinkowskiEngine.`')
/media/navlab/GNSS/work/detection/tr3d/mmdet3d/models/dense_heads/tr3d_head.py:6: UserWarning: Please follow `getting_started.md` to install MinkowskiEngine.`
  'Please follow `getting_started.md` to install MinkowskiEngine.`')
/media/navlab/GNSS/work/detection/tr3d/mmdet3d/models/detectors/mink_single_stage.py:8: UserWarning: Please follow `getting_started.md` to install MinkowskiEngine.`
  'Please follow `getting_started.md` to install MinkowskiEngine.`')
/media/navlab/GNSS/work/detection/tr3d/mmdet3d/models/detectors/tr3d_ff.py:8: UserWarning: Please follow `getting_started.md` to install MinkowskiEngine.`
  'Please follow `getting_started.md` to install MinkowskiEngine.`')
/media/navlab/GNSS/work/detection/tr3d/mmdet3d/models/necks/tr3d_neck.py:7: UserWarning: Please follow `getting_started.md` to install MinkowskiEngine.`
  'Please follow `getting_started.md` to install MinkowskiEngine.`')
Traceback (most recent call last):
  File "/home/navlab/anaconda3/envs/TR3D-113/lib/python3.7/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/media/navlab/GNSS/work/detection/tr3d/mmdet3d/models/backbones/mink_resnet.py", line 58, in __init__
    self.conv1 = ME.MinkowskiConvolution(
NameError: name 'ME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/navlab/anaconda3/envs/TR3D-113/lib/python3.7/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/media/navlab/GNSS/work/detection/tr3d/mmdet3d/models/detectors/mink_single_stage.py", line 43, in __init__
    self.backbone = build_backbone(backbone)
  File "/media/navlab/GNSS/work/detection/tr3d/mmdet3d/models/builder.py", line 34, in build_backbone
    return BACKBONES.build(cfg)
  File "/home/navlab/anaconda3/envs/TR3D-113/lib/python3.7/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/navlab/anaconda3/envs/TR3D-113/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/navlab/anaconda3/envs/TR3D-113/lib/python3.7/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
NameError: MinkResNet: name 'ME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/navlab/GNSS/work/detection/tr3d-main/demo/pcd_demo_used_ok.py", line 34, in <module>
    main()
  File "/media/navlab/GNSS/work/detection/tr3d-main/demo/pcd_demo_used_ok.py", line 19, in main
    model = init_model(args.config, args.checkpoint, device=args.device)
  File "/media/navlab/GNSS/work/detection/tr3d/mmdet3d/apis/inference.py", line 60, in init_model
    model = build_model(config.model, test_cfg=config.get('test_cfg'))
  File "/media/navlab/GNSS/work/detection/tr3d/mmdet3d/models/builder.py", line 122, in build_model
    return build_detector(cfg, train_cfg=train_cfg, test_cfg=test_cfg)
  File "/media/navlab/GNSS/work/detection/tr3d/mmdet3d/models/builder.py", line 93, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/navlab/anaconda3/envs/TR3D-113/lib/python3.7/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/navlab/anaconda3/envs/TR3D-113/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/navlab/anaconda3/envs/TR3D-113/lib/python3.7/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
NameError: MinkSingleStage3DDetector: MinkResNet: name 'ME' is not defined
______

**Comment by filaPro** [comment]
Your conda environment doesn't see installed MInkowskiEngine. You can check it with `import MinkowskiEngine`.

**Comment by mostafa501** [comment]
ok, thank you for your reply. I tried much methods to solve this error, however I got this error when installing MinkowskiEngine:
(TR3D-113) navlab@navlab-ProLiant-DL380-Gen10:~$ pip install MinkowskiEngine
Collecting MinkowskiEngine
  Using cached MinkowskiEngine-0.5.4.tar.gz (246 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch in ./anaconda3/envs/TR3D-113/lib/python3.7/site-packages (from MinkowskiEngine) (1.12.1)
Requirement already satisfied: numpy in ./anaconda3/envs/TR3D-113/lib/python3.7/site-packages (from MinkowskiEngine) (1.21.5)
Requirement already satisfied: typing_extensions in ./anaconda3/envs/TR3D-113/lib/python3.7/site-packages (from torch->MinkowskiEngine) (4.7.1)
Building wheels for collected packages: MinkowskiEngine
  Building wheel for MinkowskiEngine (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      WARNING: Skipping MinkowskiEngine as it is not installed.
      --------------------------------
      | CUDA compilation set         |
      --------------------------------
      
      Using BLAS=openblas
      Using the default compiler
      running bdist_wheel
      /home/navlab/anaconda3/envs/TR3D-113/lib/python3.7/site-packages/torch/utils/cpp_extension.py:411: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.7
      creating build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/MinkowskiCommon.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/MinkowskiKernelGenerator.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/diagnostics.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/MinkowskiConvolution.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/MinkowskiBroadcast.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/MinkowskiPruning.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/MinkowskiFunctional.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/MinkowskiInterpolation.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/MinkowskiNetwork.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/MinkowskiNonlinearity.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/MinkowskiTensor.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/MinkowskiPooling.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/MinkowskiUnion.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/__init__.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/MinkowskiChannelwiseConvolution.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/MinkowskiOps.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/MinkowskiCoordinateManager.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/sparse_matrix_functions.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/MinkowskiSparseTensor.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/MinkowskiNormalization.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/MinkowskiTensorField.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      creating build/lib.linux-x86_64-3.7/MinkowskiEngine/utils
      copying ./MinkowskiEngine/utils/summary.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine/utils
      copying ./MinkowskiEngine/utils/collation.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine/utils
      copying ./MinkowskiEngine/utils/quantization.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine/utils
      copying ./MinkowskiEngine/utils/torchsummary.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine/utils
      copying ./MinkowskiEngine/utils/coords.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine/utils
      copying ./MinkowskiEngine/utils/__init__.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine/utils
      copying ./MinkowskiEngine/utils/init.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine/utils
      copying ./MinkowskiEngine/utils/gradcheck.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine/utils
      creating build/lib.linux-x86_64-3.7/MinkowskiEngine/modules
      copying ./MinkowskiEngine/modules/senet_block.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine/modules
      copying ./MinkowskiEngine/modules/resnet_block.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine/modules
      copying ./MinkowskiEngine/modules/__init__.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine/modules
      running build_ext
      error: [Errno 2] No such file or directory: '/usr/local/cuda/bin/nvcc': '/usr/local/cuda/bin/nvcc'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for MinkowskiEngine
  Running setup.py clean for MinkowskiEngine
Failed to build MinkowskiEngine
Installing collected packages: MinkowskiEngine
  Running setup.py install for MinkowskiEngine ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for MinkowskiEngine did not run successfully.
  │ exit code: 1
  ╰─> [53 lines of output]
      WARNING: Skipping MinkowskiEngine as it is not installed.
      --------------------------------
      | CUDA compilation set         |
      --------------------------------
      
      Using BLAS=openblas
      Using the default compiler
      running install
      /home/navlab/anaconda3/envs/TR3D-113/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        setuptools.SetuptoolsDeprecationWarning,
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.7
      creating build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/MinkowskiCommon.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/MinkowskiKernelGenerator.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/diagnostics.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/MinkowskiConvolution.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/MinkowskiBroadcast.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/MinkowskiPruning.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/MinkowskiFunctional.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/MinkowskiInterpolation.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/MinkowskiNetwork.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/MinkowskiNonlinearity.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/MinkowskiTensor.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/MinkowskiPooling.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/MinkowskiUnion.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/__init__.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/MinkowskiChannelwiseConvolution.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/MinkowskiOps.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/MinkowskiCoordinateManager.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/sparse_matrix_functions.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/MinkowskiSparseTensor.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/MinkowskiNormalization.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      copying ./MinkowskiEngine/MinkowskiTensorField.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
      creating build/lib.linux-x86_64-3.7/MinkowskiEngine/utils
      copying ./MinkowskiEngine/utils/summary.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine/utils
      copying ./MinkowskiEngine/utils/collation.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine/utils
      copying ./MinkowskiEngine/utils/quantization.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine/utils
      copying ./MinkowskiEngine/utils/torchsummary.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine/utils
      copying ./MinkowskiEngine/utils/coords.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine/utils
      copying ./MinkowskiEngine/utils/__init__.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine/utils
      copying ./MinkowskiEngine/utils/init.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine/utils
      copying ./MinkowskiEngine/utils/gradcheck.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine/utils
      creating build/lib.linux-x86_64-3.7/MinkowskiEngine/modules
      copying ./MinkowskiEngine/modules/senet_block.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine/modules
      copying ./MinkowskiEngine/modules/resnet_block.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine/modules
      copying ./MinkowskiEngine/modules/__init__.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine/modules
      running build_ext
      /home/navlab/anaconda3/envs/TR3D-113/lib/python3.7/site-packages/torch/utils/cpp_extension.py:411: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      error: [Errno 2] No such file or directory: '/usr/local/cuda/bin/nvcc': '/usr/local/cuda/bin/nvcc'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> MinkowskiEngine

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
(TR3D-113) navlab@navlab-ProLiant-DL380-Gen10:~$ 

__________________________________________________________________________________________________________________
Although i have insatlled these libraries and cuda:
(TR3D-113) navlab@navlab-ProLiant-DL380-Gen10:~$ pip list
Package                 Version      Editable project location
----------------------- ------------ --------------------------------------
absl-py                 2.0.0
addict                  2.4.0
aliyun-python-sdk-core  2.14.0
aliyun-python-sdk-kms   2.16.2
anyio                   3.7.1
argon2-cffi             23.1.0
argon2-cffi-bindings    21.2.0
attrs                   23.1.0
backcall                0.2.0
beautifulsoup4          4.12.2
black                   23.3.0
bleach                  6.0.0
brotlipy                0.7.0
cachetools              5.3.2
certifi                 2022.12.7
cffi                    1.15.0
chamfer                 2.0.0
charset-normalizer      2.0.4
click                   8.1.7
colorama                0.4.6
comm                    0.1.4
crcmod                  1.7
cryptography            39.0.1
cycler                  0.11.0
debugpy                 1.7.0
decorator               5.1.1
defusedxml              0.7.1
descartes               1.1.0
emd-ext                 0.0.0
entrypoints             0.4
exceptiongroup          1.1.3
fastjsonschema          2.18.1
fire                    0.5.0
flake8                  3.9.2
fonttools               4.38.0
google-auth             2.23.4
google-auth-oauthlib    0.4.6
grpcio                  1.59.2
idna                    3.4
imageio                 2.31.2
importlib-metadata      6.7.0
importlib-resources     5.12.0
iniconfig               2.0.0
ipykernel               6.16.2
ipython                 7.34.0
ipython-genutils        0.2.0
ipywidgets              8.1.1
jedi                    0.19.1
Jinja2                  3.1.2
jmespath                0.10.0
joblib                  1.3.2
jsonschema              4.17.3
jupyter                 1.0.0
jupyter_client          7.4.9
jupyter-console         6.6.3
jupyter_core            4.12.0
jupyter-server          1.24.0
jupyterlab-pygments     0.2.2
jupyterlab-widgets      3.0.9
kiwisolver              1.4.5
llvmlite                0.36.0
lyft-dataset-sdk        0.0.8
Markdown                3.4.4
markdown-it-py          2.2.0
MarkupSafe              2.1.3
matplotlib              3.5.3
matplotlib-inline       0.1.6
mccabe                  0.6.1
mdurl                   0.1.2
mistune                 3.0.2
mkl-fft                 1.3.1
mkl-random              1.2.2
mkl-service             2.4.0
mmcls                   0.25.0
mmcv-full               1.6.0
mmdet                   2.24.1
mmdet3d                 1.0.0rc3     /media/navlab/GNSS/work/detection/tr3d
mmsegmentation          0.24.1
model-index             0.1.11
mypy-extensions         1.0.0
nbclassic               1.0.0
nbclient                0.7.4
nbconvert               7.6.0
nbformat                5.8.0
nest-asyncio            1.5.8
networkx                2.2
notebook                6.5.6
notebook_shim           0.2.3
numba                   0.53.0
numpy                   1.21.5
nuscenes-devkit         1.1.9
oauthlib                3.2.2
opencv-python           4.8.1.78
opendatalab             0.0.10
openmim                 0.3.9
openxlab                0.0.10
ordered-set             4.1.0
oss2                    2.17.0
packaging               23.2
pandas                  1.1.5
pandocfilters           1.5.0
parso                   0.8.3
pathspec                0.11.2
pexpect                 4.8.0
pickleshare             0.7.5
Pillow                  9.4.0
pip                     22.3.1
pkgutil_resolve_name    1.3.10
platformdirs            3.11.0
plotly                  5.18.0
pluggy                  1.2.0
plyfile                 0.7.4
prettytable             3.7.0
prometheus-client       0.17.1
prompt-toolkit          3.0.39
protobuf                3.20.3
psutil                  5.9.6
ptyprocess              0.7.0
pyasn1                  0.5.0
pyasn1-modules          0.3.0
pycocotools             2.0.7
pycodestyle             2.7.0
pycparser               2.21
pycryptodome            3.19.0
pyflakes                2.3.1
Pygments                2.16.1
pyOpenSSL               23.0.0
pyparsing               3.1.1
pyquaternion            0.9.9
pyrsistent              0.19.3
PySocks                 1.7.1
pytest                  7.4.3
python-dateutil         2.8.2
pytz                    2023.3.post1
PyWavelets              1.3.0
PyYAML                  6.0.1
pyzmq                   24.0.1
qtconsole               5.4.4
QtPy                    2.4.1
requests                2.28.2
requests-oauthlib       1.3.1
rich                    13.6.0
rsa                     4.9
scikit-image            0.19.3
scikit-learn            1.0.2
scipy                   1.7.3
Send2Trash              1.8.2
setuptools              60.2.0
shapely                 2.0.2
six                     1.16.0
sniffio                 1.3.0
soupsieve               2.4.1
tabulate                0.9.0
tenacity                8.2.3
tensorboard             2.11.2
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.1
termcolor               2.3.0
terminado               0.17.1
terminaltables          3.1.10
threadpoolctl           3.1.0
tifffile                2021.11.2
tinycss2                1.2.1
tomli                   2.0.1
torch                   1.12.1
torchaudio              0.12.1
torchvision             0.13.1
tornado                 6.2
tqdm                    4.65.2
traitlets               5.9.0
trimesh                 2.35.39
typed-ast               1.5.5
typing_extensions       4.7.1
urllib3                 1.26.14
wcwidth                 0.2.9
webencodings            0.5.1
websocket-client        1.6.1
Werkzeug                2.2.3
wheel                   0.38.4
widgetsnbextension      4.0.9
yapf                    0.40.2
zipp                    3.15.0
(TR3D-113) navlab@navlab-ProLiant-DL380-Gen10:~$ 
_________________________________________________________________

(TR3D-113) navlab@navlab-ProLiant-DL380-Gen10:~$ nvidia-smi
Wed Nov  8 14:30:18 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.223.02   Driver Version: 470.223.02   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  Off  | 00000000:37:00.0 Off |                    0 |
| N/A   50C    P0    29W / 250W |      9MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     45508      G   /usr/lib/xorg/Xorg                  4MiB |
|    0   N/A  N/A     46266      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+
(TR3D-113) navlab@navlab-ProLiant-DL380-Gen10:~$ 


could you please help me how to solve this error to use the network?, sorry for long reply.

**Comment by filaPro** [comment]
Looks like error speaks for itself: `error: [Errno 2] No such file or directory: '/usr/local/cuda/bin/nvcc'` .

**Comment by mostafa501** [comment]
@filaPro, can you help me solve this error please?

**Comment by filaPro** [comment]
It is not connected with TR3D or even MinkowskiEngine, just install nvcc for your OS.

**Comment by mostafa501** [comment]
ok, when i used command of nvidia-smi (i got cuda 11.4), but when i used nvcc --version (i got cuda 10.1).
I ask, if i have on my system CUDA 10.1, can I still use this model or i have to change cuda version?
thank you

________________________________________________________________________________________________________________________________
(TR3D-113) navlab@navlab-ProLiant-DL380-Gen10:/media/navlab/GNSS/work/detection/tr3d-main/MinkowskiEngine$ nvidia-smi
Wed Nov  8 18:49:23 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.223.02   Driver Version: 470.223.02   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  Off  | 00000000:37:00.0 Off |                    0 |
| N/A   49C    P0    29W / 250W |      9MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     45508      G   /usr/lib/xorg/Xorg                  4MiB |
|    0   N/A  N/A     46266      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+
(TR3D-113) navlab@navlab-ProLiant-DL380-Gen10:/media/navlab/GNSS/work/detection/tr3d-main/MinkowskiEngine$ echo $CUDA_HOME
/usr/local/cuda
(TR3D-113) navlab@navlab-ProLiant-DL380-Gen10:/media/navlab/GNSS/work/detection/tr3d-main/MinkowskiEngine$ unset CUDA_HOME
(TR3D-113) navlab@navlab-ProLiant-DL380-Gen10:/media/navlab/GNSS/work/detection/tr3d-main/MinkowskiEngine$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
(TR3D-113) navlab@navlab-ProLiant-DL380-Gen10:/med

**Comment by mostafa501** [comment]
Hi @filaPro, thank you for your replies to me, i completed with my cuda version, and i passes these errors, and now i am using this file for test and detect the classes in the point clouds:

from argparse import ArgumentParser
from mmdet3d.apis import inference_detector, init_model

# from mmdet3d.apis import show_result_meshlab

def main():
    parser = ArgumentParser()
    parser.add_argument('--pcd', default='/media/navlab/GNSS/work/detection/tr3d-main/indoor_data/table.bin', help='Point cloud file')
    parser.add_argument('--config', default='/media/navlab/GNSS/work/detection/tr3d-main/tr3d/configs/tr3d/tr3d_scannet-3d-18class.py', help='Config file')
    parser.add_argument('--checkpoint', default='/media/navlab/GNSS/work/detection/tr3d-main/pretrained_models/3d_detetction/scannet/tr3d_scannet.pth', help='Checkpoint file')
    parser.add_argument('--device', default='cuda:0', help='Device used for inference')
    parser.add_argument('--score-thr', type=float, default=0.0, help='bbox score threshold')
    parser.add_argument('--out-dir', type=str, default='/media/navlab/GNSS/work/detection/tr3d-main/evaluate_results/try1', help='dir to save results')
    parser.add_argument('--show',action='store_true',help='show online visualization results')
    parser.add_argument('--snapshot',action='store_true',help='whether to save online visualization results')
    
    args = parser.parse_args()

    # build the model from a config file and a checkpoint file
    model = init_model(args.config, args.checkpoint, device=args.device)
    # test a single image
    result, data = inference_detector(model, args.pcd)

    # show the results
    # show_result_meshlab(
    #     data,
    #     result,
    #     args.out_dir,
    #     args.score_thr,
    #     show=args.show,
    #     snapshot=args.snapshot,
    #     task='det')

if __name__ == '__main__':
    main()
_________________________________________________________________________________________________________________________________
However, i got this error, which i can not solve, and this error is frequent when using different configs files in tr3d folder.

(open-mmlab) navlab@navlab-ProLiant-DL380-Gen10:/media/navlab/GNSS/work/detection/tr3d-main$ /home/navlab/anaconda3/envs/open-mmlab/bin/python /media/navlab/GNSS/work/detection/tr3d-main/demo/pcd_demo_used_ok.py
Traceback (most recent call last):
  File "/media/navlab/GNSS/work/detection/tr3d-main/demo/pcd_demo_used_ok.py", line 36, in <module>
    main()
  File "/media/navlab/GNSS/work/detection/tr3d-main/demo/pcd_demo_used_ok.py", line 21, in main
    model = init_model(args.config, args.checkpoint, device=args.device)
  File "/media/navlab/GNSS/work/detection/tr3d-main/mmdetection3d/mmdet3d/apis/inference.py", line 69, in init_model
    model = MODELS.build(config.model)
  File "/home/navlab/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/navlab/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/navlab/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
TypeError: __init__() got an unexpected keyword argument 'voxel_size'
___________________________________________________________________________________________________________________________
Could you please help me solve this error and complete testing my point cloud file?
