### ISSUE TITLE
What is label2level in TR3Dhead?

### ISSUE THREAD

**Issue by fangchuan** [SamsungLabs/tr3d#21]
Hi, thanks a lot for this outstanding work!
currently, I am working on training my dataset using TR3D, when I adapt this code base to my dataset, I find there is a network configuration parameter that varies from dataset to dataset.
More specifically, it is the label2level in xxxx_config.py of each dataset, I notice that different scene data use different label2level, So, what is it?  Why are these configs different? And does it really matter when I want to get more accurate detection results for my dataset?

https://github.com/SamsungLabs/tr3d/blob/fa82f458a01c7ee0f24f21fd021b89a81223caeb/configs/tr3d/tr3d_sunrgbd-3d-10class.py#L21

https://github.com/SamsungLabs/tr3d/blob/fa82f458a01c7ee0f24f21fd021b89a81223caeb/configs/tr3d/tr3d_scannet-3d-18class.py#L21

@filaPro thanks in advance !

**Comment by filaPro** [comment]
Hi @fangchuan ,
Please follow #9.

**Comment by fangchuan** [comment]
> Hi @fangchuan , Please follow #9.

That's helpful, many thanks!
