### ISSUE TITLE
Matching procedure

### ISSUE THREAD

**Issue by florianlanger** [SamsungLabs/tr3d#24]
Hi Danila,
Thanks for your great work! How exactly does the matching procedure work during training ? What predictions are matched to GT objects and which are not ? Is there a distance cut off i.e. if the predicted bounding box center is more than some distance from the nearest GT bounding box it does not get matched ? When searching for the matching GT box is only that category considered which  has the highest predicted probability ? Is NMS applied also during training ? I only saw a parameter for the nms threshold specified for test time.
Thank you!

**Comment by filaPro** [comment]
Hi @florianlanger ,
We don use NMS during training. Have you followed the matching function code [here](https://github.com/SamsungLabs/tr3d/blob/main/mmdet3d/models/dense_heads/tr3d_head.py#L303)? We have 3 conditions there to match gt and predicted boxes.

**Comment by florianlanger** [comment]
Thanks for pointing me to this! So the way I understand it now is that each GT bounding box gets assigned the top_pts_threshold=6 closest predictions (at the right feature level depending if objects from that category are typically small or large) and it is also ensured that each prediction is only assigned to its closest GT bounding box, but not to multiple ones. Is that correct ?

**Comment by filaPro** [comment]
yes, that's right
