### ISSUE TITLE
Will this model be suitable for Outdoor object detection tasks ?

### ISSUE THREAD

**Issue by jediofgever** [SamsungLabs/tr3d#5]
Hello

Very nice work, thanks for the open source.
I am wondering about the potential of this model for an outdoor case. Could provide a insight into this? Is this model suitable for LiDAR object detection for the purpose of autonomous driving.

thank you

**Comment by filaPro** [comment]
Hi @jediofgever ,

I think my answer [here](https://github.com/SamsungLabs/fcaf3d/issues/45#issuecomment-1382088739) is still relevant.
