### ISSUE TITLE
ImportError: cannot import name 'print_log' from 'mmcv' 

### ISSUE THREAD

**Issue by LiMxStar** [SamsungLabs/tr3d#6]
Hello author, I encountered this issue after reconfiguring the environment. I am using cuda11.4-mmcv2.0.0. Do you have a solution? Looking forward to hearing from you.

**Comment by filaPro** [comment]
Hi @LiMxStar ,
Please follow our Dockerfile for library versions including `mmcv-full==1.6.0`.
